### GENERAL SETTINGS ###

# Site settings
title: MLT
description: "MLT is an open source multimedia framework, designed and
              developed for television broadcasting."
analytics: #Google analytics code in the format XX-nnnnnnnn-n
baseurl: ""
url: "https://mltframework.org"
timezone: "America/Los_Angeles"

gems: ["jekyll-paginate"]
paginate: 5
paginate_path: "/blog/page:num/"

# Build settings
markdown: kramdown
permalink: /:categories/:title/
excerpt_separator: <!--more--> #use this in posts to define how long the excerpt of the post (that is shown on the Blog page) is

colors:  #in hex code if not noted else
  primary: "#c80000" #"#F70031"
  primary_rgb: "200,0,0" #"247,0,49" #rgb of the primary. Needed in some places for the transparency effect.
  secondary: "#384452" #"#33004D"
  link: "#428bca"
  link_hover: "#01b2fe"
  footer_heading: "#ffffff"
  footer_content: "#bfc9d3"
  bar_background: "#f0f0f0"
  bar_foreground: "black"

defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
    values:
      layout: "standard"

collections:
  - featured_projects

### CONTACT SETTINGS ###

# Social networks usernames. Many more available: google-plus, flickr, linkedin, etc). Shown in footer.
social:
  - title: google-plus
    url: https://plus.google.com/+MltframeworkOrg
  - title: facebook
    url: https://www.facebook.com/MLTframework/
  - title: twitter
    url: https://twitter.com/MLTframework

# Postal address (add as many lines as necessary). Shown in footer and on Contact page.
address:
  - lines:
    - Some Ave, 987,
    - 23890, New York,
    - United States.
email: hello@solidtheme.com
tel: +34 8493-4893


### GENERAL DATA FOR VARIOUS LOCATIONS ###

# Short text about your company. Shown in footer on every page and also separately on Home and Contact page.
about: "MLT enables you to author, manage, and run multitrack audio/video compositions.
        <br>See our <a href=\"/halloffame/\">Hall of Fame</a><br>
        Copyright &copy; 2008-2018 by <a href=\"https://www.meltytech.com/\">Meltytech, LLC.</a>"
